### PR TITLE
Tidy and simplify code

### PR DESCRIPTION
**Pull request by jlapeyre**
* Remove unused variable.
* Make a gratuitously mutable struct immutable. And gratuitously non-constant globals constant.
* Make a function type stable.
* Remove unnecessary type conversion.

### CODE REVIEW

**Comment by blakejohnson** [comment]
Sorry I didn't pay attention to this earlier, but the changes LGTM.

**Comment by matthewware** [comment]
With #25 merged, I can delete this PR?

**Comment by jlapeyre** [comment]
> With #25 merged, I can delete this PR?

Yes. Everything here has been merged with #25.

**Comment by matthewware** [comment]
Thanks @jlapeyre !!

**Pull request closed without merging**
